// This file is generated by Slice Machine. Update with care!

import Accordian from './Accordian';
import General from './General';
import Hero from './Hero';
import Projects from './Projects';

export {
	Accordian,
	General,
	Hero,
	Projects,
};

export const components = {
	accordian: Accordian,
	general: General,
	hero: Hero,
	projects: Projects,
};
